# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
    "iPhone 14 Pro Max",
    "iPhone 14 Plus",
    "iPhone 8 Plus",
    "iPad Pro (12.9-inch) (6th generation)",
    "iPad Pro (12.9-inch) (2nd generation)"
 ])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# launch_arguments(["-appearance light"])
dark_mode(false)

# The name of the scheme which contains the UI Tests
 scheme("Snapshot")

# Where should the resulting screenshots be stored?
 output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
 clear_previous_screenshots(true)

override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
